"""
Traduccions d'UbiDiscover.
Per afegir un idioma: copia el bloc "en", tradueix els textos i afegeix-lo a
LANGUAGES amb el seu nom natiu. Les claus {entre_claus} no es tradueixen.
"""

LANGUAGES = {
    "ca": "Català",
    "es": "Español",
    "en": "English",
    "fr": "Français",
    "it": "Italiano",
    "pt": "Português",
    "de": "Deutsch",
}

DEFAULT = "en"

STRINGS = {
    # ------------------------------------------------------------------ CA
    "ca": {
        "col_ip": "IP", "col_ips": "Altres IPs", "col_mac": "MAC", "col_hostname": "Nom",
        "col_model": "Model", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Mode", "col_uptime": "Temps actiu",
        "btn_scan_local": "Escaneja xarxa local",
        "lbl_range": "Rang (CIDR):",
        "btn_scan_range": "Escaneja rang",
        "lbl_timeout": "Temps (s):",
        "btn_donate": "♥ Dona suport",
        "btn_export": "Exporta CSV",
        "btn_clear": "Neteja",
        "ctx_open": "Obre la web",
        "ctx_copy_ip": "Copia la IP",
        "ctx_copy_mac": "Copia la MAC",
        "ctx_remove_temp": "Treu IPs temporals del PC",
        "st_ready": "Llest. IPs locals: {ips}",
        "menu_help": "Ajuda",
        "menu_updates": "Comprova actualitzacions",
        "menu_donate": "Fes una donació",
        "menu_web": "Web: acollbordas.com",
        "menu_github": "Codi a GitHub",
        "menu_about": "Quant a {app}",
        "menu_language": "Idioma",
        "st_update_err": "No s'ha pogut comprovar si hi ha actualitzacions: {err}",
        "upd_title": "Actualitzacions",
        "upd_latest": "Tens la darrera versió (v{ver}).",
        "upd_new_title": "Nova versió disponible",
        "upd_new_msg": "Hi ha una versió nova: {tag}\nTu tens la v{ver}.\n\nVols actualitzar-la ara? {app} es tancarà i es tornarà a obrir automàticament.",
        "upd_progress_title": "Actualitzant {app}",
        "upd_downloading": "Descarregant {tag}...",
        "upd_verifying": "Verificant el fitxer (SHA256)...",
        "upd_restarting": "Instal·lant i reiniciant...",
        "upd_failed": "No s'ha pogut actualitzar automàticament:\n{err}\n\nVols obrir la pàgina de descàrrega?",
        "upd_bad_hash": "El fitxer descarregat no ha superat la verificació SHA256.",
        "upd_no_asset": "No s'ha trobat el fitxer {name} a la release.",
        "menu_auto_update": "Actualitza automàticament",
        "don_title": "Dona suport",
        "don_free_app": "{app} és gratuït.",
        "don_text": "Si t'és útil, pots convidar-me a un cafè via PayPal:",
        "don_amount": "Import lliure:",
        "don_button": "Dona",
        "don_thanks": "Gràcies! ♥",
        "err_amount_title": "Import",
        "err_amount": "Introdueix un import vàlid.",
        "about_text": "Descobridor de dispositius Ubiquiti (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nProgramari lliure (llicència MIT).",
        "st_scanning": "Escanejant...",
        "err_range_title": "Rang",
        "err_range_format": "Format no vàlid. Exemple: 10.20.0.0/24",
        "err_range_big": "Massa adreces (màx. {max}).",
        "st_opened": "Obert: {url}",
        "st_done": "Fet. {n} dispositius trobats.",
        "st_scanning_n": "Escanejant... {n} trobats",
        "st_checking": "Comprovant quina IP respon...",
        "st_no_access": "No hi ha accés a {ip}. Afegeix una IP del seu rang a la targeta de xarxa.",
        "tmp_title": "Equip no accessible",
        "tmp_msg": "No hi ha connexió amb {ips}.\n\n"
                   "Vols afegir una IP temporal lliure del rang {range} a la targeta de xarxa "
                   "per arribar a {target}?\n"
                   "(es comprova per ARP que no estigui ocupada; primera opció: {first})\n\n"
                   "Cal permís d'administrador. La IP desapareix en reiniciar "
                   "o des del menú «Treu IPs temporals».",
        "st_cancelled": "Cancel·lat",
        "st_no_admin": "No s'ha pogut executar com a administrador",
        "st_finding_ip": "Buscant una IP lliure (comprovació ARP)...",
        "st_all_busy": "Totes les IPs provades estan ocupades o no s'han pogut afegir",
        "st_temp_added": "IP temporal {ip} afegida. Esperant que {target} respongui...",
        "st_temp_timeout": "Temps esgotat esperant la IP temporal (UAC cancel·lat?)",
        "st_no_response": "{ip} continua sense respondre",
        "st_no_temp": "No hi ha IPs temporals afegides",
        "st_removed": "Eliminades: {ips}",
        "tmp_exit_title": "IPs temporals",
        "tmp_exit_msg": "Vols treure les IPs temporals abans de sortir?",
        "st_exported": "Exportat a {path}",
    },
    # ------------------------------------------------------------------ ES
    "es": {
        "col_ip": "IP", "col_ips": "Otras IPs", "col_mac": "MAC", "col_hostname": "Nombre",
        "col_model": "Modelo", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Modo", "col_uptime": "Tiempo activo",
        "btn_scan_local": "Escanear red local",
        "lbl_range": "Rango (CIDR):",
        "btn_scan_range": "Escanear rango",
        "lbl_timeout": "Tiempo (s):",
        "btn_donate": "♥ Apoya el proyecto",
        "btn_export": "Exportar CSV",
        "btn_clear": "Limpiar",
        "ctx_open": "Abrir la web",
        "ctx_copy_ip": "Copiar la IP",
        "ctx_copy_mac": "Copiar la MAC",
        "ctx_remove_temp": "Quitar IPs temporales del PC",
        "st_ready": "Listo. IPs locales: {ips}",
        "menu_help": "Ayuda",
        "menu_updates": "Buscar actualizaciones",
        "menu_donate": "Hacer una donación",
        "menu_web": "Web: acollbordas.com",
        "menu_github": "Código en GitHub",
        "menu_about": "Acerca de {app}",
        "menu_language": "Idioma",
        "st_update_err": "No se ha podido comprobar si hay actualizaciones: {err}",
        "upd_title": "Actualizaciones",
        "upd_latest": "Tienes la última versión (v{ver}).",
        "upd_new_title": "Nueva versión disponible",
        "upd_new_msg": "Hay una versión nueva: {tag}\nTienes la v{ver}.\n\n¿Quieres actualizar ahora? {app} se cerrará y se volverá a abrir automáticamente.",
        "upd_progress_title": "Actualizando {app}",
        "upd_downloading": "Descargando {tag}...",
        "upd_verifying": "Verificando el archivo (SHA256)...",
        "upd_restarting": "Instalando y reiniciando...",
        "upd_failed": "No se ha podido actualizar automáticamente:\n{err}\n\n¿Quieres abrir la página de descarga?",
        "upd_bad_hash": "El archivo descargado no ha superado la verificación SHA256.",
        "upd_no_asset": "No se ha encontrado el archivo {name} en la release.",
        "menu_auto_update": "Actualizar automáticamente",
        "don_title": "Apoya el proyecto",
        "don_free_app": "{app} es gratuito.",
        "don_text": "Si te resulta útil, puedes invitarme a un café vía PayPal:",
        "don_amount": "Importe libre:",
        "don_button": "Donar",
        "don_thanks": "¡Gracias! ♥",
        "err_amount_title": "Importe",
        "err_amount": "Introduce un importe válido.",
        "about_text": "Descubridor de dispositivos Ubiquiti (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nSoftware libre (licencia MIT).",
        "st_scanning": "Escaneando...",
        "err_range_title": "Rango",
        "err_range_format": "Formato no válido. Ejemplo: 10.20.0.0/24",
        "err_range_big": "Demasiadas direcciones (máx. {max}).",
        "st_opened": "Abierto: {url}",
        "st_done": "Hecho. {n} dispositivos encontrados.",
        "st_scanning_n": "Escaneando... {n} encontrados",
        "st_checking": "Comprobando qué IP responde...",
        "st_no_access": "Sin acceso a {ip}. Añade una IP de su rango a la tarjeta de red.",
        "tmp_title": "Equipo no accesible",
        "tmp_msg": "No hay conexión con {ips}.\n\n"
                   "¿Quieres añadir una IP temporal libre del rango {range} a la tarjeta de red "
                   "para llegar a {target}?\n"
                   "(se comprueba por ARP que no esté ocupada; primera opción: {first})\n\n"
                   "Se necesitan permisos de administrador. La IP desaparece al reiniciar "
                   "o desde el menú «Quitar IPs temporales».",
        "st_cancelled": "Cancelado",
        "st_no_admin": "No se ha podido ejecutar como administrador",
        "st_finding_ip": "Buscando una IP libre (comprobación ARP)...",
        "st_all_busy": "Todas las IPs probadas están ocupadas o no se han podido añadir",
        "st_temp_added": "IP temporal {ip} añadida. Esperando a que {target} responda...",
        "st_temp_timeout": "Tiempo agotado esperando la IP temporal (¿UAC cancelado?)",
        "st_no_response": "{ip} sigue sin responder",
        "st_no_temp": "No hay IPs temporales añadidas",
        "st_removed": "Eliminadas: {ips}",
        "tmp_exit_title": "IPs temporales",
        "tmp_exit_msg": "¿Quieres quitar las IPs temporales antes de salir?",
        "st_exported": "Exportado a {path}",
    },
    # ------------------------------------------------------------------ EN
    "en": {
        "col_ip": "IP", "col_ips": "Other IPs", "col_mac": "MAC", "col_hostname": "Name",
        "col_model": "Model", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Mode", "col_uptime": "Uptime",
        "btn_scan_local": "Scan local network",
        "lbl_range": "Range (CIDR):",
        "btn_scan_range": "Scan range",
        "lbl_timeout": "Timeout (s):",
        "btn_donate": "♥ Support",
        "btn_export": "Export CSV",
        "btn_clear": "Clear",
        "ctx_open": "Open web interface",
        "ctx_copy_ip": "Copy IP",
        "ctx_copy_mac": "Copy MAC",
        "ctx_remove_temp": "Remove temporary IPs from PC",
        "st_ready": "Ready. Local IPs: {ips}",
        "menu_help": "Help",
        "menu_updates": "Check for updates",
        "menu_donate": "Make a donation",
        "menu_web": "Web: acollbordas.com",
        "menu_github": "Source code on GitHub",
        "menu_about": "About {app}",
        "menu_language": "Language",
        "st_update_err": "Could not check for updates: {err}",
        "upd_title": "Updates",
        "upd_latest": "You have the latest version (v{ver}).",
        "upd_new_title": "New version available",
        "upd_new_msg": "A new version is available: {tag}\nYou have v{ver}.\n\nUpdate now? {app} will close and reopen automatically.",
        "upd_progress_title": "Updating {app}",
        "upd_downloading": "Downloading {tag}...",
        "upd_verifying": "Verifying file (SHA256)...",
        "upd_restarting": "Installing and restarting...",
        "upd_failed": "Automatic update failed:\n{err}\n\nOpen the download page?",
        "upd_bad_hash": "The downloaded file failed SHA256 verification.",
        "upd_no_asset": "File {name} was not found in the release.",
        "menu_auto_update": "Update automatically",
        "don_title": "Support the project",
        "don_free_app": "{app} is free.",
        "don_text": "If you find it useful, you can buy me a coffee via PayPal:",
        "don_amount": "Custom amount:",
        "don_button": "Donate",
        "don_thanks": "Thank you! ♥",
        "err_amount_title": "Amount",
        "err_amount": "Please enter a valid amount.",
        "about_text": "Ubiquiti device discovery tool (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nFree software (MIT license).",
        "st_scanning": "Scanning...",
        "err_range_title": "Range",
        "err_range_format": "Invalid format. Example: 10.20.0.0/24",
        "err_range_big": "Too many addresses (max. {max}).",
        "st_opened": "Opened: {url}",
        "st_done": "Done. {n} devices found.",
        "st_scanning_n": "Scanning... {n} found",
        "st_checking": "Checking which IP responds...",
        "st_no_access": "No access to {ip}. Add an IP from its subnet to your network adapter.",
        "tmp_title": "Device unreachable",
        "tmp_msg": "Cannot connect to {ips}.\n\n"
                   "Add a free temporary IP from the {range} range to your network adapter "
                   "to reach {target}?\n"
                   "(ARP is used to check it is not in use; first choice: {first})\n\n"
                   "Administrator rights are required. The IP is removed on reboot "
                   "or from the 'Remove temporary IPs' menu.",
        "st_cancelled": "Cancelled",
        "st_no_admin": "Could not run as administrator",
        "st_finding_ip": "Looking for a free IP (ARP check)...",
        "st_all_busy": "All tested IPs are in use or could not be added",
        "st_temp_added": "Temporary IP {ip} added. Waiting for {target} to respond...",
        "st_temp_timeout": "Timed out waiting for the temporary IP (UAC cancelled?)",
        "st_no_response": "{ip} is still not responding",
        "st_no_temp": "No temporary IPs have been added",
        "st_removed": "Removed: {ips}",
        "tmp_exit_title": "Temporary IPs",
        "tmp_exit_msg": "Remove the temporary IPs before exiting?",
        "st_exported": "Exported to {path}",
    },
    # ------------------------------------------------------------------ FR
    "fr": {
        "col_ip": "IP", "col_ips": "Autres IP", "col_mac": "MAC", "col_hostname": "Nom",
        "col_model": "Modèle", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Mode", "col_uptime": "Uptime",
        "btn_scan_local": "Scanner le réseau local",
        "lbl_range": "Plage (CIDR) :",
        "btn_scan_range": "Scanner la plage",
        "lbl_timeout": "Délai (s) :",
        "btn_donate": "♥ Soutenir",
        "btn_export": "Exporter CSV",
        "btn_clear": "Effacer",
        "ctx_open": "Ouvrir l'interface web",
        "ctx_copy_ip": "Copier l'IP",
        "ctx_copy_mac": "Copier la MAC",
        "ctx_remove_temp": "Retirer les IP temporaires du PC",
        "st_ready": "Prêt. IP locales : {ips}",
        "menu_help": "Aide",
        "menu_updates": "Rechercher des mises à jour",
        "menu_donate": "Faire un don",
        "menu_web": "Web : acollbordas.com",
        "menu_github": "Code source sur GitHub",
        "menu_about": "À propos de {app}",
        "menu_language": "Langue",
        "st_update_err": "Impossible de vérifier les mises à jour : {err}",
        "upd_title": "Mises à jour",
        "upd_latest": "Vous avez la dernière version (v{ver}).",
        "upd_new_title": "Nouvelle version disponible",
        "upd_new_msg": "Une nouvelle version est disponible : {tag}\nVous avez la v{ver}.\n\nMettre à jour maintenant ? {app} se fermera et se rouvrira automatiquement.",
        "upd_progress_title": "Mise à jour de {app}",
        "upd_downloading": "Téléchargement de {tag}...",
        "upd_verifying": "Vérification du fichier (SHA256)...",
        "upd_restarting": "Installation et redémarrage...",
        "upd_failed": "La mise à jour automatique a échoué :\n{err}\n\nOuvrir la page de téléchargement ?",
        "upd_bad_hash": "Le fichier téléchargé n'a pas passé la vérification SHA256.",
        "upd_no_asset": "Le fichier {name} est introuvable dans la release.",
        "menu_auto_update": "Mettre à jour automatiquement",
        "don_title": "Soutenir le projet",
        "don_free_app": "{app} est gratuit.",
        "don_text": "S'il vous est utile, vous pouvez m'offrir un café via PayPal :",
        "don_amount": "Montant libre :",
        "don_button": "Donner",
        "don_thanks": "Merci ! ♥",
        "err_amount_title": "Montant",
        "err_amount": "Veuillez saisir un montant valide.",
        "about_text": "Outil de découverte d'appareils Ubiquiti (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nLogiciel libre (licence MIT).",
        "st_scanning": "Analyse en cours...",
        "err_range_title": "Plage",
        "err_range_format": "Format non valide. Exemple : 10.20.0.0/24",
        "err_range_big": "Trop d'adresses (max. {max}).",
        "st_opened": "Ouvert : {url}",
        "st_done": "Terminé. {n} appareils trouvés.",
        "st_scanning_n": "Analyse en cours... {n} trouvés",
        "st_checking": "Recherche de l'IP qui répond...",
        "st_no_access": "Pas d'accès à {ip}. Ajoutez une IP de son sous-réseau à votre carte réseau.",
        "tmp_title": "Appareil inaccessible",
        "tmp_msg": "Impossible de se connecter à {ips}.\n\n"
                   "Ajouter une IP temporaire libre de la plage {range} à la carte réseau "
                   "pour atteindre {target} ?\n"
                   "(l'ARP permet de vérifier qu'elle n'est pas utilisée ; premier choix : {first})\n\n"
                   "Droits d'administrateur requis. L'IP disparaît au redémarrage "
                   "ou via le menu « Retirer les IP temporaires ».",
        "st_cancelled": "Annulé",
        "st_no_admin": "Impossible d'exécuter en tant qu'administrateur",
        "st_finding_ip": "Recherche d'une IP libre (vérification ARP)...",
        "st_all_busy": "Toutes les IP testées sont occupées ou n'ont pas pu être ajoutées",
        "st_temp_added": "IP temporaire {ip} ajoutée. En attente de la réponse de {target}...",
        "st_temp_timeout": "Délai dépassé en attendant l'IP temporaire (UAC annulé ?)",
        "st_no_response": "{ip} ne répond toujours pas",
        "st_no_temp": "Aucune IP temporaire ajoutée",
        "st_removed": "Supprimées : {ips}",
        "tmp_exit_title": "IP temporaires",
        "tmp_exit_msg": "Retirer les IP temporaires avant de quitter ?",
        "st_exported": "Exporté vers {path}",
    },
    # ------------------------------------------------------------------ IT
    "it": {
        "col_ip": "IP", "col_ips": "Altri IP", "col_mac": "MAC", "col_hostname": "Nome",
        "col_model": "Modello", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Modalità", "col_uptime": "Uptime",
        "btn_scan_local": "Scansiona rete locale",
        "lbl_range": "Intervallo (CIDR):",
        "btn_scan_range": "Scansiona intervallo",
        "lbl_timeout": "Timeout (s):",
        "btn_donate": "♥ Sostieni",
        "btn_export": "Esporta CSV",
        "btn_clear": "Pulisci",
        "ctx_open": "Apri interfaccia web",
        "ctx_copy_ip": "Copia IP",
        "ctx_copy_mac": "Copia MAC",
        "ctx_remove_temp": "Rimuovi IP temporanei dal PC",
        "st_ready": "Pronto. IP locali: {ips}",
        "menu_help": "Aiuto",
        "menu_updates": "Controlla aggiornamenti",
        "menu_donate": "Fai una donazione",
        "menu_web": "Web: acollbordas.com",
        "menu_github": "Codice sorgente su GitHub",
        "menu_about": "Informazioni su {app}",
        "menu_language": "Lingua",
        "st_update_err": "Impossibile controllare gli aggiornamenti: {err}",
        "upd_title": "Aggiornamenti",
        "upd_latest": "Hai l'ultima versione (v{ver}).",
        "upd_new_title": "Nuova versione disponibile",
        "upd_new_msg": "È disponibile una nuova versione: {tag}\nHai la v{ver}.\n\nAggiornare ora? {app} si chiuderà e si riaprirà automaticamente.",
        "upd_progress_title": "Aggiornamento di {app}",
        "upd_downloading": "Download di {tag}...",
        "upd_verifying": "Verifica del file (SHA256)...",
        "upd_restarting": "Installazione e riavvio...",
        "upd_failed": "Aggiornamento automatico non riuscito:\n{err}\n\nAprire la pagina di download?",
        "upd_bad_hash": "Il file scaricato non ha superato la verifica SHA256.",
        "upd_no_asset": "File {name} non trovato nella release.",
        "menu_auto_update": "Aggiorna automaticamente",
        "don_title": "Sostieni il progetto",
        "don_free_app": "{app} è gratuito.",
        "don_text": "Se ti è utile, puoi offrirmi un caffè tramite PayPal:",
        "don_amount": "Importo libero:",
        "don_button": "Dona",
        "don_thanks": "Grazie! ♥",
        "err_amount_title": "Importo",
        "err_amount": "Inserisci un importo valido.",
        "about_text": "Strumento di rilevamento dispositivi Ubiquiti (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nSoftware libero (licenza MIT).",
        "st_scanning": "Scansione in corso...",
        "err_range_title": "Intervallo",
        "err_range_format": "Formato non valido. Esempio: 10.20.0.0/24",
        "err_range_big": "Troppi indirizzi (max {max}).",
        "st_opened": "Aperto: {url}",
        "st_done": "Fatto. {n} dispositivi trovati.",
        "st_scanning_n": "Scansione in corso... {n} trovati",
        "st_checking": "Verifica di quale IP risponde...",
        "st_no_access": "Nessun accesso a {ip}. Aggiungi un IP della sua sottorete alla scheda di rete.",
        "tmp_title": "Dispositivo non raggiungibile",
        "tmp_msg": "Impossibile connettersi a {ips}.\n\n"
                   "Aggiungere un IP temporaneo libero dell'intervallo {range} alla scheda di rete "
                   "per raggiungere {target}?\n"
                   "(tramite ARP si verifica che non sia in uso; prima scelta: {first})\n\n"
                   "Sono necessari i permessi di amministratore. L'IP viene rimosso al riavvio "
                   "o dal menu «Rimuovi IP temporanei».",
        "st_cancelled": "Annullato",
        "st_no_admin": "Impossibile eseguire come amministratore",
        "st_finding_ip": "Ricerca di un IP libero (verifica ARP)...",
        "st_all_busy": "Tutti gli IP provati sono occupati o non è stato possibile aggiungerli",
        "st_temp_added": "IP temporaneo {ip} aggiunto. In attesa che {target} risponda...",
        "st_temp_timeout": "Tempo scaduto in attesa dell'IP temporaneo (UAC annullato?)",
        "st_no_response": "{ip} continua a non rispondere",
        "st_no_temp": "Nessun IP temporaneo aggiunto",
        "st_removed": "Rimossi: {ips}",
        "tmp_exit_title": "IP temporanei",
        "tmp_exit_msg": "Rimuovere gli IP temporanei prima di uscire?",
        "st_exported": "Esportato in {path}",
    },
    # ------------------------------------------------------------------ PT
    "pt": {
        "col_ip": "IP", "col_ips": "Outros IPs", "col_mac": "MAC", "col_hostname": "Nome",
        "col_model": "Modelo", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Modo", "col_uptime": "Uptime",
        "btn_scan_local": "Analisar rede local",
        "lbl_range": "Intervalo (CIDR):",
        "btn_scan_range": "Analisar intervalo",
        "lbl_timeout": "Tempo (s):",
        "btn_donate": "♥ Apoiar",
        "btn_export": "Exportar CSV",
        "btn_clear": "Limpar",
        "ctx_open": "Abrir interface web",
        "ctx_copy_ip": "Copiar IP",
        "ctx_copy_mac": "Copiar MAC",
        "ctx_remove_temp": "Remover IPs temporários do PC",
        "st_ready": "Pronto. IPs locais: {ips}",
        "menu_help": "Ajuda",
        "menu_updates": "Procurar atualizações",
        "menu_donate": "Fazer um donativo",
        "menu_web": "Web: acollbordas.com",
        "menu_github": "Código-fonte no GitHub",
        "menu_about": "Sobre o {app}",
        "menu_language": "Idioma",
        "st_update_err": "Não foi possível verificar as atualizações: {err}",
        "upd_title": "Atualizações",
        "upd_latest": "Tem a versão mais recente (v{ver}).",
        "upd_new_title": "Nova versão disponível",
        "upd_new_msg": "Está disponível uma nova versão: {tag}\nTem a v{ver}.\n\nAtualizar agora? O {app} será fechado e reaberto automaticamente.",
        "upd_progress_title": "A atualizar o {app}",
        "upd_downloading": "A transferir {tag}...",
        "upd_verifying": "A verificar o ficheiro (SHA256)...",
        "upd_restarting": "A instalar e a reiniciar...",
        "upd_failed": "Não foi possível atualizar automaticamente:\n{err}\n\nAbrir a página de transferência?",
        "upd_bad_hash": "O ficheiro transferido não passou a verificação SHA256.",
        "upd_no_asset": "O ficheiro {name} não foi encontrado na release.",
        "menu_auto_update": "Atualizar automaticamente",
        "don_title": "Apoiar o projeto",
        "don_free_app": "O {app} é gratuito.",
        "don_text": "Se lhe for útil, pode oferecer-me um café através do PayPal:",
        "don_amount": "Montante livre:",
        "don_button": "Doar",
        "don_thanks": "Obrigado! ♥",
        "err_amount_title": "Montante",
        "err_amount": "Introduza um montante válido.",
        "about_text": "Ferramenta de deteção de dispositivos Ubiquiti (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nSoftware livre (licença MIT).",
        "st_scanning": "A analisar...",
        "err_range_title": "Intervalo",
        "err_range_format": "Formato inválido. Exemplo: 10.20.0.0/24",
        "err_range_big": "Demasiados endereços (máx. {max}).",
        "st_opened": "Aberto: {url}",
        "st_done": "Concluído. {n} dispositivos encontrados.",
        "st_scanning_n": "A analisar... {n} encontrados",
        "st_checking": "A verificar que IP responde...",
        "st_no_access": "Sem acesso a {ip}. Adicione um IP da sua sub-rede à placa de rede.",
        "tmp_title": "Equipamento inacessível",
        "tmp_msg": "Sem ligação a {ips}.\n\n"
                   "Adicionar um IP temporário livre do intervalo {range} à placa de rede "
                   "para chegar a {target}?\n"
                   "(verifica-se por ARP que não está em uso; primeira opção: {first})\n\n"
                   "São necessárias permissões de administrador. O IP desaparece ao reiniciar "
                   "ou através do menu «Remover IPs temporários».",
        "st_cancelled": "Cancelado",
        "st_no_admin": "Não foi possível executar como administrador",
        "st_finding_ip": "A procurar um IP livre (verificação ARP)...",
        "st_all_busy": "Todos os IPs testados estão ocupados ou não foi possível adicioná-los",
        "st_temp_added": "IP temporário {ip} adicionado. A aguardar resposta de {target}...",
        "st_temp_timeout": "Tempo esgotado à espera do IP temporário (UAC cancelado?)",
        "st_no_response": "{ip} continua sem responder",
        "st_no_temp": "Não há IPs temporários adicionados",
        "st_removed": "Removidos: {ips}",
        "tmp_exit_title": "IPs temporários",
        "tmp_exit_msg": "Remover os IPs temporários antes de sair?",
        "st_exported": "Exportado para {path}",
    },
    # ------------------------------------------------------------------ DE
    "de": {
        "col_ip": "IP", "col_ips": "Weitere IPs", "col_mac": "MAC", "col_hostname": "Name",
        "col_model": "Modell", "col_firmware": "Firmware", "col_essid": "SSID",
        "col_wmode": "Modus", "col_uptime": "Laufzeit",
        "btn_scan_local": "Lokales Netz scannen",
        "lbl_range": "Bereich (CIDR):",
        "btn_scan_range": "Bereich scannen",
        "lbl_timeout": "Timeout (s):",
        "btn_donate": "♥ Unterstützen",
        "btn_export": "CSV exportieren",
        "btn_clear": "Leeren",
        "ctx_open": "Weboberfläche öffnen",
        "ctx_copy_ip": "IP kopieren",
        "ctx_copy_mac": "MAC kopieren",
        "ctx_remove_temp": "Temporäre IPs vom PC entfernen",
        "st_ready": "Bereit. Lokale IPs: {ips}",
        "menu_help": "Hilfe",
        "menu_updates": "Nach Updates suchen",
        "menu_donate": "Spenden",
        "menu_web": "Web: acollbordas.com",
        "menu_github": "Quellcode auf GitHub",
        "menu_about": "Über {app}",
        "menu_language": "Sprache",
        "st_update_err": "Updates konnten nicht geprüft werden: {err}",
        "upd_title": "Updates",
        "upd_latest": "Sie haben die neueste Version (v{ver}).",
        "upd_new_title": "Neue Version verfügbar",
        "upd_new_msg": "Eine neue Version ist verfügbar: {tag}\nIhre Version: v{ver}.\n\nJetzt aktualisieren? {app} wird geschlossen und automatisch neu gestartet.",
        "upd_progress_title": "{app} wird aktualisiert",
        "upd_downloading": "{tag} wird heruntergeladen...",
        "upd_verifying": "Datei wird geprüft (SHA256)...",
        "upd_restarting": "Installation und Neustart...",
        "upd_failed": "Automatische Aktualisierung fehlgeschlagen:\n{err}\n\nDownload-Seite öffnen?",
        "upd_bad_hash": "Die heruntergeladene Datei hat die SHA256-Prüfung nicht bestanden.",
        "upd_no_asset": "Datei {name} wurde im Release nicht gefunden.",
        "menu_auto_update": "Automatisch aktualisieren",
        "don_title": "Projekt unterstützen",
        "don_free_app": "{app} ist kostenlos.",
        "don_text": "Wenn es Ihnen nützt, können Sie mir über PayPal einen Kaffee spendieren:",
        "don_amount": "Freier Betrag:",
        "don_button": "Spenden",
        "don_thanks": "Danke! ♥",
        "err_amount_title": "Betrag",
        "err_amount": "Bitte einen gültigen Betrag eingeben.",
        "about_text": "Erkennungstool für Ubiquiti-Geräte (airOS, UniFi, EdgeMAX...).\n\n"
                      "Albert Coll Bordas\n{web}\n{repo}\n\nFreie Software (MIT-Lizenz).",
        "st_scanning": "Scan läuft...",
        "err_range_title": "Bereich",
        "err_range_format": "Ungültiges Format. Beispiel: 10.20.0.0/24",
        "err_range_big": "Zu viele Adressen (max. {max}).",
        "st_opened": "Geöffnet: {url}",
        "st_done": "Fertig. {n} Geräte gefunden.",
        "st_scanning_n": "Scan läuft... {n} gefunden",
        "st_checking": "Prüfe, welche IP antwortet...",
        "st_no_access": "Kein Zugriff auf {ip}. Fügen Sie Ihrem Netzwerkadapter eine IP aus dessen Subnetz hinzu.",
        "tmp_title": "Gerät nicht erreichbar",
        "tmp_msg": "Keine Verbindung zu {ips}.\n\n"
                   "Eine freie temporäre IP aus dem Bereich {range} zum Netzwerkadapter hinzufügen, "
                   "um {target} zu erreichen?\n"
                   "(per ARP wird geprüft, dass sie nicht belegt ist; erste Wahl: {first})\n\n"
                   "Administratorrechte erforderlich. Die IP wird beim Neustart "
                   "oder über das Menü „Temporäre IPs entfernen“ gelöscht.",
        "st_cancelled": "Abgebrochen",
        "st_no_admin": "Konnte nicht als Administrator ausgeführt werden",
        "st_finding_ip": "Suche freie IP (ARP-Prüfung)...",
        "st_all_busy": "Alle getesteten IPs sind belegt oder konnten nicht hinzugefügt werden",
        "st_temp_added": "Temporäre IP {ip} hinzugefügt. Warte auf Antwort von {target}...",
        "st_temp_timeout": "Zeitüberschreitung beim Warten auf die temporäre IP (UAC abgebrochen?)",
        "st_no_response": "{ip} antwortet weiterhin nicht",
        "st_no_temp": "Keine temporären IPs hinzugefügt",
        "st_removed": "Entfernt: {ips}",
        "tmp_exit_title": "Temporäre IPs",
        "tmp_exit_msg": "Temporäre IPs vor dem Beenden entfernen?",
        "st_exported": "Exportiert nach {path}",
    },
}


def detect_system_language():
    """Codi d'idioma del sistema (p. ex. 'ca') si està suportat, si no DEFAULT."""
    code = ""
    try:
        import ctypes
        import locale
        lcid = ctypes.windll.kernel32.GetUserDefaultUILanguage()
        code = locale.windows_locale.get(lcid, "")
    except Exception:
        import locale
        import os
        code = (locale.getlocale()[0] or os.environ.get("LANG", "") or "")
    code = code.split("_")[0].split("-")[0].lower()
    return code if code in LANGUAGES else DEFAULT


class Translator:
    def __init__(self, lang=DEFAULT):
        self.set(lang)

    def set(self, lang):
        self.lang = lang if lang in STRINGS else DEFAULT

    def __call__(self, key, **kw):
        txt = STRINGS[self.lang].get(key) or STRINGS[DEFAULT].get(key) or key
        return txt.format(**kw) if kw else txt
